name: QT Workflow

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.9'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw53'  
    - name: Test qmake
      run: |
         $Qt5_DIR/bin/qmake.exe  hmc.pro
         ls $Qt5_DIR/bin/
         #sudo apt-get install -y mingw-w53
         #mingw-w64
