name: QT Workflow

on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.11.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw53'  
    - name: qmake
      run: |
        dir D:/a/carnetMedicalNumerique-V2/Qt/5.11.0/
        D:/a/carnetMedicalNumerique-V2/Qt/5.12.9/mingw53_32/bin/qmake.exe hmc.pro
    - name: make
      run: make
    - name: Download a single artifact
      uses: actions/upload-artifact@v2
      with:
        name: hmc
        path: |
          bin/hmc.exe
          D:/a/carnetMedicalNumerique-V2/Qt/5.11.0/mingw53_32/bin/*.dll
